---
version: 2

build:
  image: testing
  apt_packages:
    - python3-dev
    - libmysqlclient-dev

sphinx:
  configuration: docs/conf.py

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
