# Generated by Django 2.1 on 2018-12-11 00:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import grimoirelab_toolkit.datetime
import sortinghat.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created_at', sortinghat.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', sortinghat.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('alpha3', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sortinghat.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', sortinghat.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('domain', models.CharField(max_length=128)),
                ('is_top_domain', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'domains_organizations',
                'ordering': ('domain',),
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sortinghat.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', sortinghat.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('start', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('end', models.DateTimeField(default=datetime.datetime(2100, 1, 1, 0, 0))),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('created_at', sortinghat.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', sortinghat.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('email', models.CharField(max_length=128, null=True)),
                ('username', models.CharField(max_length=128, null=True)),
                ('source', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'identities',
            },
        ),
        migrations.CreateModel(
            name='MatchingBlacklist',
            fields=[
                ('created_at', sortinghat.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', sortinghat.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('excluded', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'matching_blacklist',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sortinghat.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', sortinghat.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('name', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sortinghat.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', sortinghat.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('email', models.CharField(max_length=128, null=True)),
                ('gender', models.CharField(max_length=32, null=True)),
                ('gender_acc', models.PositiveIntegerField(null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('country', models.ForeignKey(db_column='country_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Country')),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='UniqueIdentity',
            fields=[
                ('created_at', sortinghat.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', sortinghat.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('uuid', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'uidentities',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='uidentity',
            field=models.OneToOneField(db_column='uuid', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.UniqueIdentity'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='identity',
            name='uidentity',
            field=models.ForeignKey(db_column='uuid', on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='core.UniqueIdentity'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.Organization'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='uidentity',
            field=models.ForeignKey(db_column='uuid', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.UniqueIdentity'),
        ),
        migrations.AddField(
            model_name='domain',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('alpha3',)},
        ),
        migrations.AlterUniqueTogether(
            name='identity',
            unique_together={('name', 'email', 'username', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('uidentity', 'organization', 'start', 'end')},
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('domain',)},
        ),
    ]
