# Generated by Django 3.2.18 on 2023-05-04 07:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_multi_tenancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='host',
            new_name='header',
        ),
        migrations.AlterUniqueTogether(
            name='tenant',
            unique_together={('user', 'header')},
        ),
    ]
