# Generated by Django 2.1 on 2020-03-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueidentity',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
