# Generated by Django 2.1 on 2020-04-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniqueIdentity',
            new_name='Individual',
        ),
        migrations.AlterModelTable(
            name='individual',
            table='individuals',
        ),
    ]
