# Generated by Django 3.2.19 on 2023-07-03 09:55

from django.db import migrations, models
import grimoirelab_toolkit.datetime
import sortinghat.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_using_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sortinghat.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', sortinghat.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('job_type', models.CharField(max_length=128)),
                ('interval', models.PositiveIntegerField(default=None, null=True)),
                ('args', models.JSONField(default=None, null=True)),
                ('job_id', models.CharField(default=None, max_length=128, null=True)),
                ('scheduled_datetime', models.DateTimeField(default=None, null=True)),
                ('last_execution', models.DateTimeField(default=None, null=True)),
                ('failed', models.BooleanField(default=False)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('executions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'scheduled_tasks',
            },
        ),
    ]
