# Generated by Django 2.1 on 2020-04-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_individuals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='uidentity',
            new_name='individual',
        ),
        migrations.RenameField(
            model_name='identity',
            old_name='uidentity',
            new_name='individual',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='uidentity',
            new_name='individual',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('individual', 'organization', 'start', 'end')},
        ),
    ]
