# Generated by Django 3.2.19 on 2023-07-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_unify_scheduled_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportIdentitiesTask',
        ),
    ]
