# Generated by Django 2.1 on 2020-04-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_uuid_to_mk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='id',
            new_name='uuid',
        ),
    ]
