# Generated by Django 3.1 on 2021-06-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_id_to_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ('last_modified', 'created_at', 'profile__name')},
        ),
        migrations.AlterField(
            model_name='operation',
            name='args',
            field=models.JSONField(),
        ),
    ]
