# Generated by Django 4.2.15 on 2024-08-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='perm_group',
            field=models.CharField(default='user', max_length=128),
        ),
    ]
