# Generated by Django 4.2.13 on 2024-08-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tenant_perm_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ('last_modified', 'created_at', 'profile__name', 'last_reviewed')},
        ),
        migrations.AddField(
            model_name='individual',
            name='last_reviewed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
