# Generated by Django 5.2.8 on 2025-12-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_individual_options_individual_last_reviewed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['target'], name='op_target'),
        ),
    ]
