# Generated by Django 3.1 on 2021-07-28 10:33

from django.db import migrations, models
import grimoirelab_toolkit.datetime
import sortinghat.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommenderExclusionTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sortinghat.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', sortinghat.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('term', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'recommender_exclusion_terms',
                'unique_together': {('term',)},
            },
        ),
        migrations.DeleteModel(
            name='MatchingBlacklist',
        ),
    ]
