# Generated by Django 3.1 on 2022-02-01 16:08

from django.db import migrations
from sortinghat.core.models import Group

def migrate_organizations(apps, schema_editor):
    Organization = apps.get_model('core', 'Organization')
    for organization in Organization.objects.all():
        group = Group.add_root(name=organization.name,
                               id=organization.id,
                               created_at=organization.created_at,
                               type='organization')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_group'),
    ]

    operations = [
        migrations.RunPython(migrate_organizations, reverse_code=migrations.RunPython.noop),
    ]
