# Generated by Django 3.1 on 2022-02-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_group_proxies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='organization',
            new_name='parent_org',
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'parent_org')},
        ),
    ]
