# Generated by Django 3.1 on 2022-02-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_group_parent_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='organization',
            new_name='group',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('individual', 'group', 'start', 'end')},
        ),
    ]
