# Generated by Django 3.1 on 2022-10-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_organization_to_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('execute_job', 'Can execute a job'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
