# Generated by Django 3.1 on 2022-12-16 11:31

from django.db import migrations, models
import django.db.models.deletion
import grimoirelab_toolkit.datetime
import sortinghat.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_custompermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sortinghat.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', sortinghat.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('applied', models.BooleanField(default=None, null=True)),
                ('individual1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_recommendation_individual_1', to='core.individual')),
                ('individual2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_recommendation_individual_2', to='core.individual')),
            ],
            options={
                'db_table': 'merge_recommendations',
                'unique_together': {('individual1', 'individual2')},
            },
        ),
        migrations.CreateModel(
            name='GenderRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sortinghat.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', sortinghat.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('gender', models.CharField(max_length=128)),
                ('accuracy', models.PositiveIntegerField()),
                ('applied', models.BooleanField(default=None, null=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.individual')),
            ],
            options={
                'db_table': 'gender_recommendations',
                'unique_together': {('individual',)},
            },
        ),
        migrations.CreateModel(
            name='AffiliationRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sortinghat.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', sortinghat.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('applied', models.BooleanField(default=None, null=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.individual')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
            ],
            options={
                'db_table': 'affiliation_recommendations',
                'unique_together': {('individual', 'organization')},
            },
        ),
    ]
